spring.datasource.url=jdbc:postgresql://localhost:5432/authify_app
spring.datasource.username=authify
spring.datasource.password=ruslan4321!

spring.jpa.hibernate.ddl-auto=update

jwt.secret.key=thisismysecretkeyievercreatedinmydevelopmentcareer

server.servlet.context-path=/api/v1.0

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a4a6ba001@smtp-brevo.com
spring.mail.password=xsmtpsib-c868ac58bd9834f43e58c9d9d51c6e04cd34907a7a8153031b88b47f82e8fd8a-YoViv10cdGImoV5N
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=gregprom5@gmail.com
